apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: griot-grits-aa488b
commonLabels:
  app: minio

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- console-route.yaml
- object-storage-route.yaml
